//! ビルドスクリプト。
//! Tauri のビルドに加え、配布リソース（scripts/*.jsx と pdfium.dll）の SHA-256 を
//! 算出し、`$OUT_DIR/integrity_manifest.rs` に「期待ハッシュ表(門番の鍵)」として出力する。
//! これを本体に include! して、実行時に実ファイルと照合する（改ざん/別ファイル検出）。

use sha2::{Digest, Sha256};
use std::fs;
use std::path::Path;

fn sha256_hex(path: &Path) -> Option<String> {
    let data = fs::read(path).ok()?;
    let mut hasher = Sha256::new();
    hasher.update(&data);
    Some(
        hasher
            .finalize()
            .iter()
            .map(|b| format!("{:02x}", b))
            .collect(),
    )
}

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let mut entries: Vec<(String, String)> = Vec::new();

    // scripts/*.jsx を全てハッシュ化
    let scripts_dir = Path::new(&manifest_dir).join("scripts");
    println!("cargo:rerun-if-changed=scripts");
    if let Ok(read) = fs::read_dir(&scripts_dir) {
        let mut files: Vec<_> = read
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().map(|x| x == "jsx").unwrap_or(false))
            .collect();
        files.sort();
        for f in files {
            if let (Some(name), Some(hash)) =
                (f.file_name().and_then(|n| n.to_str()), sha256_hex(&f))
            {
                entries.push((format!("scripts/{}", name), hash));
            }
        }
    }

    // fail-closed: scripts/*.jsx を1件もハッシュ化できなければビルドを中止する。
    // （読み取り失敗等で空マニフェストのまま配布すると、整合性ゲートが全スクリプトで
    //   実質無効化されてしまうため。正常ビルドでは scripts に必ず .jsx がある。）
    let script_hash_count = entries
        .iter()
        .filter(|(name, _)| name.starts_with("scripts/"))
        .count();
    if script_hash_count == 0 {
        panic!(
            "integrity build: scripts/*.jsx を1件もハッシュ化できませんでした（{} を確認）。\
             空の整合性マニフェストでの配布を防ぐためビルドを中止します。",
            scripts_dir.display()
        );
    }

    // pdfium.dll（存在すれば。CI/ローカルで未配置の場合はスキップ）
    let pdfium = Path::new(&manifest_dir)
        .join("resources")
        .join("pdfium")
        .join("pdfium.dll");
    println!("cargo:rerun-if-changed=resources/pdfium/pdfium.dll");
    if let Some(hash) = sha256_hex(&pdfium) {
        entries.push(("resources/pdfium/pdfium.dll".to_string(), hash));
    }

    // マニフェスト(Rustソース)を出力
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("integrity_manifest.rs");
    let mut src = String::new();
    src.push_str(
        "// AUTO-GENERATED by build.rs — リソースの期待 SHA-256（門番の鍵）。手で編集しない。\n",
    );
    src.push_str("pub static RESOURCE_HASHES: &[(&str, &str)] = &[\n");
    for (name, hash) in &entries {
        src.push_str(&format!("    ({:?}, {:?}),\n", name, hash));
    }
    src.push_str("];\n");
    fs::write(&dest, src).expect("write integrity_manifest.rs");

    tauri_build::build();
}
